/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getDominantColorCallback(x: number, y: number, width: number, height: number, interval: number, callback: (arg0: Array<string>) => null): void
